apiVersion: apps/v1
kind: Deployment
metadata:
    name: microservice-seguridad-deploy
    lables:
        name: microservice-seguridad-deploy
        app: microservice
    spec:
        replicas: 2
        selector: 
            matchLabels:
                app: microservice-seguridad
                type: microservice
        template: 
            metadata:
                name: microservice-seguridad-pod
                labels:
                    app: microservice-seguridad
                    type: microservice
            spec:
                containers:
                - name: microservice-seguridad-app
                  image: spblue/serviciosapiseguridad:latest
                  ports:
                    - containerPort: 80
                  env:
                   - name: ConnectionStrings__ConexionDB
                     value: Server=mssql-service;Database=Seguridad;User=sa;Password:$cspilapa2025