apiVersion: v1
kind: Pod
metadata:
    name: microservice-librerira-pod
    labels:
        app: microservice-libreria
        type: microservice
spec:
    containers:
    - name: microservice-libreria-app
      image: spblue/serviciosapilibreria:latest
      ports:
        - containerPort: 80