apiVersion: v1
kind: Pod
metadata:
    name: mongo-pod
    labels:
        app: microservice-libreria
        name: mongo-pod
spec:
    containers:
    - name: mongo
      image: mongo
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "cspilapa"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "$cspilapa2025"
      ports:
        - containerPort: 27017
