apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql-deploy
    labels:
        app: microservice-seguridad    
        name: msql-deploy
    spec:
        replicas: 1
        selector:
            matchLables:
                app: microservice-seguridad
                name: mssql-pod
        template:
            metadata:
                name: mssql-pod
                labels:
                    app: microservice-seguridad
                    name: mssql-pod
            spec:
                containers:
                - name: mssql
                  image: mcr.microsoft.com/mssql/server
                  ports:
                    - containerPort: 1433
                  env:
                  - name: ACCEPT_EULA
                    value: "Y"
                  - name: SA_PASSWORD
                    value: "$cspilapa2025"
